### ISSUE TITLE
Full Xcode installation required

### ISSUE THREAD

**Issue by brejoc** [jwbargsten/defbro#3]
When installing `defbro` via `brew install jwbargsten/misc/defbro`, I get the following error message:

```
…
Tapped 1 formula (16 files, 14.1KB).
defbro: A full installation of Xcode.app >= 11.2 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.
Error: defbro: An unsatisfied requirement failed this build.
```

Is there really a full install of Xcode necessary or would the cli tools also be enough?

**Comment by jwbargsten** [comment]
I checked it shortly, it unfortunately seems: yes. However, perhaps this pkg could be "bottled", meaning homebrew would use a pre-compiled binary.

**Comment by brejoc** [comment]
Having it bottles sounds like a good solution, since a full Xcode installation isn't something everybody is looking forward to. And thanks for looking into this!

**Comment by megclaypool** [comment]
I'd appreciate having a "bottled" package -- I'm trying to use this package to set up an automation to switch default browsers depending on my focus, but I can't install Xcode on my little old MacBook Air without upgrading the system. Since I've only got 8G of RAM, I think I'm better off sticking with an older version of MacOS 😛

**Comment by jwbargsten** [comment]
OK, I'll see what I can do, I have some time left next week.

**Comment by LeeBinder** [comment]
@jwbargsten thank you for defbro. Did you run into an issue pouring defbro into a homebrew bottle?

**Comment by jwbargsten** [comment]
Yeah, I did. The bottling process is quite simple in itself, but to get everything running was more challenging than expected. Mostly due to lack of documentation or my inability to interpret that documentation.

Anyway, I now published a bottle for big sur. Perhaps somebody can confirm if it works.

**Comment by LeeBinder** [comment]
Well done, @jwbargsten, respect! I can even confirm defbro installation working in Ventura 13.0.1 Intel:
- defbro -> list of browsers (incl. those on other volumes)
- changed active browser to Waterfox > verified by double-clicking a .URL file

The resulting cask merely "weighs" 1.5MB. Mighty cool 👍 🥇

**Comment by jwbargsten** [comment]
Cool, nice to hear. I'll close this comment. I'll still investigate if I can create a ARM-based bottle for all M1 owners, but currently homebrew/github actions lack support.
